/**
 * GlitchTip management-API types.
 *
 * PROVENANCE — WHY THIS FILE LOOKS THE WAY IT DOES
 * -----------------------------------------------
 * The tree this was researched in is the **Angular 22.1 SPA only**; the
 * Django/DRF backend is a sibling repository and is NOT present. So field names
 * come from `src/app/api/api-schema.d.ts` (9,528 lines), which is GENERATED by
 * `openapi-typescript` from the server's own `/api/openapi.json`. Paths and
 * shapes in it are therefore server truth, not guesses.
 *
 * That also gives a drift check for a live instance: pull
 * `GET /api/openapi.json` and diff it against the checked-in schema. If a field
 * below no longer exists there, the checkout moved and this file is stale.
 *
 * FOUR TRAPS THAT ALL FAIL SILENTLY
 * ---------------------------------
 *  1. `IssueSchema.id` is a STRING, not a number.
 *  2. `IssueSchema.count` is a STRINGIFIED NUMBER. `parseInt()` it.
 *  3. `stats` tuples are `[epochSECONDS, count]` — not ms, not ISO. A chart that
 *     treats them as ms puts every datapoint in January 1970.
 *  4. `IssueEventSchema.tags` is an ARRAY OF SINGLE-KEY OBJECTS (`[{k: v}]`),
 *     not a plain map. `tags[k]` yields `undefined` and every tag lookup misses.
 *
 * Plus one trap that is not about types at all: the response body of every list
 * endpoint is a BARE JSON ARRAY, and ALL pagination metadata lives in RESPONSE
 * HEADERS. There is no `results`/`count` wrapper, no `page`/`offset` param, and
 * no body-borne cursor.
 */

/** Management API prefix. The legacy ingest paths are NOT for reading. */
export const GLITCHTIP_API_PREFIX = "/api/0/";

export const GLITCHTIP_ENV_PREFIX = "GLITCHTIP";

export interface GlitchtipConfig {
  /**
   * Host root, e.g. `https://errors.example.com`. Server default port is 8000.
   * `/api/0/` is appended by the adapter — configure the host, not the path.
   */
  baseUrl: string;
  /**
   * An APIToken, sent as `Authorization: Bearer <token>`.
   *
   * NOT the session cookie the Angular SPA itself uses, and NOT
   * `Authorization: Token <key>`, which is UNVERIFIED and not claimed here.
   */
  token: string;
  /** Per-request timeout in ms. Defaults to 30s. */
  timeoutMs?: number;
}

/* -------------------------------------------------------------------------- */
/* Auth                                                                       */
/* -------------------------------------------------------------------------- */

export function glitchtipBearerAuth(token: string): { kind: "bearer"; token: string } {
  return { kind: "bearer", token };
}

/**
 * Token scopes cannot be validated client-side.
 *
 * Tokens ARE scoped, but the scope STRINGS are never enumerated anywhere in the
 * frontend tree — there is no list to check a configured token against. So an
 * under-scoped token cannot be detected before it is used; it surfaces as a 403
 * from the first endpoint that needs the missing scope. This adapter therefore
 * does not pretend to pre-check, and `diagnostics` reports the scopes the token
 * actually has so an operator can see them.
 */
export const GLITCHTIP_TOKEN_SCOPES_ARE_UNVERIFIABLE = true;

export interface GlitchtipApiToken {
  id: number;
  label: string;
  scopes: string[];
  /** The secret itself. Only ever present on create/list responses. */
  token: string;
  created: string;
}

/* -------------------------------------------------------------------------- */
/* Root                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * `GET /api/0/` → `{version, user, auth}`.
 *
 * Doubles as the health check AND the token-verification call: a working token
 * comes back with `auth` populated, a bad one 401s. Cheaper and more decisive
 * than a dedicated ping endpoint.
 *
 * `user` is `unknown` because its shape is not established in the research, and
 * `auth` is nullable because an unauthenticated/expired session reaches this
 * route with `null` there.
 */
export interface GlitchtipRoot {
  version: string;
  user: unknown;
  auth: GlitchtipApiToken | null;
}

/* -------------------------------------------------------------------------- */
/* Pagination — cursor in, metadata in HEADERS                                */
/* -------------------------------------------------------------------------- */

export interface GlitchtipPagination {
  /** `X-Hits` — rows in THIS page. */
  hits: number;
  /** `X-Max-Hits` — total rows matching. */
  maxHits: number;
  /** Cursor for the next page, from `Link; rel="next"`. Absent on the last page. */
  next?: string;
  previous?: string;
}

export class GlitchtipPaginationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GlitchtipPaginationError";
  }
}

export const GLITCHTIP_HEADER_HITS = "X-Hits";
export const GLITCHTIP_HEADER_MAX_HITS = "X-Max-Hits";
export const GLITCHTIP_HEADER_LINK = "Link";

/**
 * Read pagination metadata out of response headers.
 *
 * A MISSING HEADER IS AN ERROR, NOT A ZERO. That is a deliberate choice and it
 * matches the frontend, whose own `getPaginationHeaders` THROWS when any of
 * `X-Hits`, `X-Max-Hits` or `Link` is absent.
 *
 * Defaulting instead would be worse than the error: with `maxHits` defaulted to
 * 0 every pager reads "0 results" on a page that returned rows, and a missing
 * `Link` on a middle page silently truncates a walk at the first hop. Both look
 * like correct, empty data. A proxy that strips `Link` — which is legal HTTP —
 * would turn into silent data loss rather than a diagnosable failure.
 */
export function parseGlitchtipPaginationHeaders(headers: Headers): GlitchtipPagination {
  const hits = headers.get(GLITCHTIP_HEADER_HITS);
  const maxHits = headers.get(GLITCHTIP_HEADER_MAX_HITS);
  const link = headers.get(GLITCHTIP_HEADER_LINK);

  const missing: string[] = [];
  if (hits === null) missing.push(GLITCHTIP_HEADER_HITS);
  if (maxHits === null) missing.push(GLITCHTIP_HEADER_MAX_HITS);
  if (link === null) missing.push(GLITCHTIP_HEADER_LINK);
  if (missing.length > 0) {
    throw new GlitchtipPaginationError(
      `glitchtip: response is missing pagination header(s) ${missing.join(", ")}. GlitchTip carries ` +
        `ALL pagination metadata in headers, so a page cannot be interpreted without them. This ` +
        `usually means a proxy stripped them, or the endpoint is not cursor-paginated.`,
    );
  }

  return {
    hits: Number(hits),
    maxHits: Number(maxHits),
    ...(nextGlitchtipCursor(link!) !== undefined ? { next: nextGlitchtipCursor(link!) } : {}),
    ...(previousGlitchtipCursor(link!) !== undefined
      ? { previous: previousGlitchtipCursor(link!) }
      : {}),
  };
}

/**
 * Pull the `cursor` out of one RFC-5988 `Link` entry.
 *
 * The header looks like:
 * `<https://host/api/0/organizations/acme/issues/?cursor=cD0yMDI2...>; rel="next"`
 *
 * The URL is echoed for humans; only its `cursor` query param matters, and it is
 * opaque. It is passed back verbatim and never constructed.
 */
function cursorFromLink(link: string | null | undefined, rel: string): string | undefined {
  if (link === null || link === undefined) return undefined;
  for (const part of link.split(",")) {
    const match = part.match(/<([^>]+)>\s*;\s*rel\s*=\s*"?([^";]+)"?/);
    if (!match) continue;
    if (match[2]!.trim() !== rel) continue;
    const cursor = new URL(match[1]!, "http://placeholder.test").searchParams.get("cursor");
    if (cursor !== null && cursor.length > 0) return cursor;
  }
  return undefined;
}

export function nextGlitchtipCursor(link: string | null | undefined): string | undefined {
  return cursorFromLink(link, "next");
}

export function previousGlitchtipCursor(link: string | null | undefined): string | undefined {
  return cursorFromLink(link, "previous");
}

/** A limit of 200 is known-good. There is no `page` or `offset` param. */
export const GLITCHTIP_LIST_LIMIT = 200;

/** One decoded list response: a bare array plus its header metadata. */
export interface GlitchtipListPage<T> {
  data: T[];
  pagination: GlitchtipPagination;
}

/* -------------------------------------------------------------------------- */
/* Organizations and projects                                                 */
/* -------------------------------------------------------------------------- */

/**
 * `OrganizationSchema`.
 *
 * `require2fa` is surfaced because it is the single most consequential security
 * flag on the deployment: an org that has not required 2FA can have an admin
 * account taken over, and that is worth showing in a diagnostics panel rather
 * than only in the GlitchTip UI.
 */
export interface GlitchtipOrganization {
  require2fa?: boolean;
  [key: string]: unknown;
}

export interface GlitchtipProject {
  id?: string;
  slug?: string;
  [key: string]: unknown;
}

export interface GlitchtipEnvironment {
  [key: string]: unknown;
}

export interface GlitchtipRelease {
  [key: string]: unknown;
}

/**
 * `GET /api/0/users/` — GLITCHTIP STAFF USERS, not end users.
 *
 * There is NO end-user listing endpoint in the product. The people whose errors
 * these are only appear denormalised inside issue events as
 * `IssueEventSchema.user`, which is `unknown`. Naming this collection "users"
 * without the qualifier is how a dashboard ends up charting its own support
 * team's headcount as if it were user impact.
 */
export type GlitchtipStaffUser = Record<string, unknown>;

/* -------------------------------------------------------------------------- */
/* Issues                                                                     */
/* -------------------------------------------------------------------------- */

export type GlitchtipIssueType = "default" | "error" | "csp";

/**
 * `stats` tuple: `[epochSECONDS, count]`.
 *
 * EPOCH SECONDS. Not milliseconds, not ISO. Declared periods are `"24h"` and
 * `"14d"`. The frontend proves it: it passes `stats?.map(([ts, val]) => [ts, val])`
 * straight through and then looks datapoints up by `datapoint.timestamp / 1000`.
 */
export type GlitchtipStatsTuple = [number, number];

export interface GlitchtipStatsPoint {
  /** Epoch MILLISECONDS, for charting. Converted from the tuple's epoch seconds. */
  timestampMs: number;
  /** The raw epoch SECONDS value, kept so a caller can see what the wire said. */
  epochSeconds: number;
  count: number;
}

/** The periods GlitchTip declares for `stats`. */
export type GlitchtipStatsPeriod = "24h" | "14d";

/**
 * `IssueSchema`.
 *
 * Two field types here are wrong in every direction a reader would assume:
 * `id` is a STRING, and `count` is a STRINGIFIED NUMBER. `project.id` is also a
 * string — while `IssueEventSchema.projectID` on the same page is a NUMBER. That
 * inconsistency is by design in the server's schema, not a typo to be tidied up.
 *
 * Members beyond the four the research pins down are left to the index
 * signature: naming a field that does not exist is worse than not naming it.
 */
export interface GlitchtipIssue {
  /** A STRING. `Number(issue.id)` on a 64-bit id loses precision. */
  id: string;
  type: GlitchtipIssueType;
  /** A STRINGIFIED NUMBER. Use {@link glitchtipIssueCount}. */
  count: string;
  project: { id: string };
  /** Keyed by period; `null` when the server has no data for it. */
  stats: Record<string, GlitchtipStatsTuple[]> | null;
  [key: string]: unknown;
}

/**
 * Coerce `IssueSchema.count` / `IssueStatsResponse.count` to a number.
 *
 * Both are stringified numbers, so a chart that adds them up gets `"12" + "3"`
 * and a 200 response that looks plausible.
 */
export function glitchtipIssueCount(value: string | number | null | undefined): number {
  if (value === null || value === undefined) return 0;
  const parsed = typeof value === "number" ? value : Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : 0;
}

/** An issue id, kept as a string. */
export function glitchtipIssueId(value: string | number): string {
  return String(value);
}

/**
 * Flatten `IssueEventSchema.stats` into charting points.
 *
 * `epochSeconds * 1000` is the whole conversion, and it is the step everyone
 * skips. Without it every datapoint lands in 1970 and the chart renders a
 * plausible-looking spike.
 *
 * `period` filters to one key when the caller wants a single series; omit it to
 * flatten every declared period.
 */
export function parseGlitchtipStats(
  stats: Record<string, GlitchtipStatsTuple[]> | null | undefined,
  period?: GlitchtipStatsPeriod | string,
): GlitchtipStatsPoint[] {
  if (!stats) return [];
  const keys = period === undefined ? Object.keys(stats) : [period];
  const points: GlitchtipStatsPoint[] = [];
  for (const key of keys) {
    for (const tuple of stats[key] ?? []) {
      const [epochSeconds, count] = tuple;
      points.push({ timestampMs: epochSeconds * 1000, epochSeconds, count });
    }
  }
  return points;
}

export type GlitchtipIssueSortField = "last_seen" | "first_seen" | "count" | "priority";

/** `-` prefix for descending. */
export type GlitchtipIssueSort = GlitchtipIssueSortField | `-${GlitchtipIssueSortField}`;

export const GLITCHTIP_ISSUE_SORT_FIELDS: readonly GlitchtipIssueSortField[] = [
  "last_seen",
  "first_seen",
  "count",
  "priority",
];

/**
 * Query for `GET /api/0/organizations/{org}/issues/`.
 *
 * NOTE WHAT IS ABSENT: `status`.
 *
 * There is no server-side status filter in this API — status filtering is
 * client-side in the Angular build. It is therefore not modelled here. Adding a
 * `status` param would send a query the server silently ignores, and the result
 * would look filtered when it is not: the worst possible failure, because the
 * numbers are plausible. (Marked UNVERIFIED upstream; if a future server adds
 * real support, this type gains the field.)
 */
export interface GlitchtipIssuesQuery {
  id?: string;
  start?: string;
  end?: string;
  /**
   * NUMERIC project ids, NOT slugs.
   *
   * A slug here returns the unfiltered set rather than an error, so the mistake
   * looks like "the filter is broken" rather than "wrong id type".
   */
  project?: number[];
  /** Repeated param. */
  environment?: string[];
  query?: string;
  sort?: GlitchtipIssueSort;
  limit?: number;
  cursor?: string;
}

export function assertGlitchtipIssueSort(sort: GlitchtipIssueSort | undefined): void {
  if (sort === undefined) return;
  const field = sort.startsWith("-") ? sort.slice(1) : sort;
  if (!GLITCHTIP_ISSUE_SORT_FIELDS.includes(field as GlitchtipIssueSortField)) {
    throw new Error(
      `glitchtip: sort "${sort}" is not one of ${GLITCHTIP_ISSUE_SORT_FIELDS.join(", ")} ` +
        `(optionally prefixed with "-" for descending).`,
    );
  }
}

/**
 * `issues-stats` — `groups` is REQUIRED.
 *
 * Omitting it is an error server-side. The value is a list of issue ids; they
 * are sent as REPEATED params, matching every other list param in this API.
 */
export interface GlitchtipIssueStatsQuery {
  /** Required. Numeric issue ids. */
  groups: number[];
  statsPeriod?: GlitchtipStatsPeriod;
}

/* -------------------------------------------------------------------------- */
/* Issue events                                                               */
/* -------------------------------------------------------------------------- */

/**
 * `IssueEventSchema`.
 *
 * `tags` is an ARRAY OF SINGLE-KEY OBJECTS — `[{ browser: "Firefox" }]` — not a
 * map. Reading `event.tags.browser` is `undefined` and every tag facet is empty
 * with no error. {@link glitchtipTagsToRecord} flattens it.
 *
 * `type` is a plain `string` here, NOT an enum, unlike `IssueSchema.type`.
 * `metadata` values are strings only. `user` is the end-user payload and is
 * `unknown` because it is unschema'd upstream — inventing fields for it would be
 * inventing an API.
 */
export interface GlitchtipIssueEvent {
  /** A NUMBER, unlike `IssueSchema.project.id`. */
  projectID: number;
  /** A plain string, NOT the `default|error|csp` enum of `IssueSchema.type`. */
  type: string;
  tags: Array<Record<string, string>>;
  metadata: Record<string, string>;
  user: unknown;
  [key: string]: unknown;
}

/** Flatten `[{k: v}]` into `{k: v}`. Later duplicates win, matching a map read. */
export function glitchtipTagsToRecord(
  tags: Array<Record<string, string>> | null | undefined,
): Record<string, string> {
  const record: Record<string, string> = {};
  for (const entry of tags ?? []) {
    for (const [key, value] of Object.entries(entry)) record[key] = value;
  }
  return record;
}

/* -------------------------------------------------------------------------- */
/* Performance                                                                */
/* -------------------------------------------------------------------------- */

/**
 * `TransactionGroupSchema`.
 *
 * `avgDuration`, `p50` and `p95` are MILLISECONDS. Do not carry a unit
 * assumption across adapters: OpenPanel's `avg_duration` on
 * `pages/performance` is MINUTES, and it is tempting to treat two
 * near-identically-named duration fields the same way.
 *
 * `errorRate` and `throughput` are serializer-computed `readonly` properties:
 * safe to read, meaningless to send.
 */
export interface GlitchtipTransactionGroup {
  /** ms. */
  avgDuration: number;
  /** ms. */
  p50: number;
  /** ms. */
  p95: number;
  /** Serializer-computed. Read only; never send. */
  readonly errorRate?: number;
  /** Serializer-computed. Read only; never send. */
  readonly throughput?: number;
  [key: string]: unknown;
}

export interface GlitchtipSpanGroup {
  [key: string]: unknown;
}

export interface GlitchtipMonitor {
  [key: string]: unknown;
}

export interface GlitchtipLog {
  [key: string]: unknown;
}

/* -------------------------------------------------------------------------- */
/* Deliberately unmodelled                                                    */
/* -------------------------------------------------------------------------- */

/**
 * `stats_v2` — NOT TYPED AND NOT EXPOSED.
 *
 * The generated schema declares NO response body for it (`content?: never`) and
 * the frontend implementation is explicitly reverse-engineered rather than
 * contract-derived. Its request is partly known — `category: "error" |
 * "transaction"`, `field: "sum(quantity)" | "sum(times_seen)"`, required `start`
 * and `end`, optional `interval: "1d" | "1h" | "1m"` (default `1h") and
 * `project?: number[]`.
 *
 * Its RESPONSE is not. Declaring one would put field names in this repository
 * that no server has confirmed, so the adapter omits the endpoint instead. It
 * must be probed against a live instance first: pull `/api/openapi.json` and, if
 * the response body is still absent there, read the DRF serializer in the backend
 * repository (not present in this tree).
 */
export type GlitchtipStatsV2 = never;

/**
 * Session replay / end-user listing: not modelled, because neither exists as a
 * readable endpoint. See {@link GlitchtipStaffUser}.
 */
export type GlitchtipEndUser = never;
